### ISSUE TITLE
Imports_helper returns error if any import has a person_id for which there is no person record

### ISSUE THREAD

**Issue by jstirnaman** [BibApp/BibApp#14]
The problem is at  
def imported_for(import)
    if import.person_id
      person = Person.find_by_id(import.person_id)

where it's possible for imports.person_id to return an ID that may no longer exist in the People table. Then Person.display_name returns an error.

You could do something like
if import.person_id
  if Person.find_by_id(import.person_id)
      person = Person.find_by_id(import.person_id)
...
but it seems the underlying cause is that imports.person_id wasn't removed when the Person record was destroyed. Not sure why in our case.

Here's the log error:
Started GET "/users/11/imports" for 10.2.104.25 at Tue May 17 11:14:04 -0500 2011
  Processing by ImportsController#index as HTML
  Parameters: {"user_id"=>"11"}
Rendered imports/index.html.haml within layouts/application (341.7ms)
Completed   in 553ms

ActionView::Template::Error (undefined method `display_name' for nil:NilClass):
    27:           %tbody
    28:             %tr
    29:               %td=link_to "Batch-#{import.id}", user_import_path(current_user, import.id)
    30:               %td=imported_for(import)
    31:               %td=import.created_at
    32:               %td=import.state
  app/helpers/imports_helper.rb:6:in`imported_for'
  app/views/imports/index.html.haml:30:in `_app_views_imports_index_html_haml___160372542_35118300_0'
  app/views/imports/index.html.haml:26:in`each'
  app/views/imports/index.html.haml:26:in `_app_views_imports_index_html_haml___160372542_35118300_0'

**Comment by hading** [comment]
I don't know exactly what I think the best thing to do here is. It would be possible to write a method that, upon destruction of a person, runs through imports and sets person_id to nil as appropriate. I'm not sure I like this because it would make imports for a person look like System imports.

I'm more inclined to conditionalize on whether a person was found - if not, then give a message like 'Deleted Person' instead so that there is some way to distinguish.

In fact, I think I'll fix it that way for now and if we decide we want something else later we can change it again then.

**Comment by hading** [comment]
Ideally the import model would have another field to record this information just for this case (when a person is deleted), but I'm not inclined to add that in unless there is actual desire to have it from someone.

**Comment by hading** [comment]
Fixed (in the simple way described above) in commit 3ab6fce.
