### ISSUE TITLE
SHERPA/RoMEO coloring

### ISSUE THREAD

**Issue by waingram** [BibApp/BibApp#19]
A feature we have been talking about for some time now: we should be displaying the Romeo color for publications and works on the view screens. We have had several requests for this and should make it a priority.

**Comment by hading** [comment]
Yeah, Sarah mentioned this to me at some point. I'll see what I can do about it.

**Comment by hading** [comment]
I'm not that knowledgeable about SHERPA/RoMEO. I've had a quick look at the website and through our code. If I understand correctly, this is something that is attached to each publisher (based on whatever that publisher's greatest restrictions are). So works and publications would inherit the RoMEO color from their publisher (if it has one). I see also that the table for Publications has a column for sherpa_id, but (even on our production site) it is nil for all rows. I also don't see anything on the SHERPA site about publication level data, so this is perhaps just unused?

Assuming the above is approximately correct there shouldn't be any grave difficulty in incorporating this information in views. It's just a matter of deciding which views get it, deciding in what manner to display it (another column? literally color something with the RoMEO color?), and making sure that the relevant controllers set the variables up efficiently (if we're incorporating it into lists of works or publications it should be just a matter of including over the publisher association when we do our query).

**Comment by waingram** [comment]
We are using the api

http://www.sherpa.ac.uk/romeo/api.html

**Comment by hading** [comment]
That may be useful. As far as I can tell Bibapp currently only does anything on the publisher level. Poking around that link a bit I'm not sure that there really is any useful information (at least in a simple form like the RoMEO color) on an individual publication basis.

Two obvious places to put the information would be the indexes for publishers (perhaps in its own column, either text or a graphic or both) and publications (in the publishers column, say with a little color graphic). I need to check my paper notes to see if Sarah mentioned anything in particular (the old Google tracker might have some information too). Otherwise I think it'd be a fine idea to start with those two index pages (which should be easy) and to make it known that we're starting to work on this and solicit opinions about where it would be helpful to see this information.

**Comment by hading** [comment]
Just for clarification, there are a lot of nooks and crannies where some publisher and/or publication information appears, so it's probably best not to try to find and do them all but to find out where people would actually find it useful to have the SHERPA/RoMEO color and just worry about it there.

**Comment by hading** [comment]
I've done some initial work on this (in the sherpa branch). Now it puts a little colored square (with tooltip) by the publisher name in a few places and puts a bit more prominent display on the page for a publisher itself. I've solicited opinions from the mailing list about where else it might be useful and also about whether there should be a global option to hide these displays (which would _almost_ leave everything the same as it is now).

**Comment by hading** [comment]
As requested on the list (I think) I put the information on the 'Upload Content File' page for a work (e.g. http://localhost:3000/works/1292/attachments/new), which is a good place for it.

If I get more input from the list I'll act on it; if not I'll get this into master soon.

To have a global option to kill this is simple - there are two partials that do all the displaying, just wrap them in a conditional. I'm still not going to do that unless someone asks, though.

**Comment by hading** [comment]
I've merged this into master. We can open up new tickets for other things that we decide we want to do with sherpa/romeo.

**Comment by waingram** [comment]
Great! Thanks for doing this.
