### ISSUE TITLE
Duplicate publication created

### ISSUE THREAD

**Issue by waingram** [BibApp/BibApp#20]
I added a new work [1] that was published in Library Trends. I filled out the new work form with the publisher/publication info. I expected the publication would have matched up with Library Trends already in the system [2], but it created a new publication record instead [3]. (We should write cucumber tests for issues like this.)
1. http://connections.ideals.illinois.edu/works/22547
2. http://connections.ideals.illinois.edu/publications/60-Library_Trends
3. http://connections.ideals.illinois.edu/publications/8760-Library_Trends

**Comment by hading** [comment]
Presumably something is going wrong with the rather complex Work.create_from_hash method (and its callees). Somewhere down the line it tries to look up the publication, and I guess it's not doing it correctly. Hopefully routine to fix once I figure out exactly where it is going off.

**Comment by waingram** [comment]
Yeah, that method is crazy. It needs to be re-thought and re-written. I can help with that.

Bill

**Comment by hading** [comment]
I have in mind to fix it at some point, but exactly when is unknown. For 
now I think I'll be content to figure out why it's not doing the right 
thing here.

I suspect that some of this sort of  stuff that crops up in Bibapp is 
from before nested forms existed in Rails, but I'm not sure that that 
would help in this particular case.

On 6/20/2011 1:54 PM, waingram wrote:

> Yeah, that method is crazy. It needs to be re-thought and re-written. I can help with that.
> 
> Bill
> 
> > -----Original Message-----
> > From: hading [mailto:reply+i-1051002-
> > e15fb7579a264d4642cc13fad2defb56e2d73f9a@reply.github.com]
> > Sent: Monday, June 20, 2011 13:52
> > To: waingram@gmail.com
> > Subject: Re: [BibApp] Duplicate publication created (#20)
> > 
> > Presumably something is going wrong with the rather complex
> > Work.create_from_hash method (and its callees). Somewhere down the line
> > it tries to look up the publication, and I guess it's not doing it correctly.
> > Hopefully routine to fix once I figure out exactly where it is going off.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/BibApp/BibApp/issues/20#issuecomment-1404894

## 

Howard Ding
hading2@gmail.com
hding2@illinois.edu

**Comment by hading** [comment]
I thought it might be another case where I previously had messed up some find_or_create methods, but I've reverted them and I'm still getting the problem. So next I guess it's into the debugger.

**Comment by hading** [comment]
I need to dig a bit more into the past of this class to see if I messed something up when I was refactoring it, but I think what is going on here currently is this - before locating the publication, it first tries to locate a publisher. If you haven't supplied a publisher then it uses 'Unknown' as the publisher. Then when trying to find a publication it takes into account both the publication name and publisher. So if the publication is present with a publisher other than 'Unknown' then it misses that because it already is using the 'Unknown' publisher and it goes ahead and creates a new publication for 'Unknown' with the given name. If you add another work with the same publication but without specifying a publisher then it will reuse Unknown as the publisher and add that work to the publication that was created the first time.

**Comment by hading** [comment]
A non-technical comment before I look further to see if this worked in the past - I'm not really sure what the right behavior here is. Note that if the publication name isn't given it will default to 'Unknown', just like the publisher. We could try looking up the publication name first, but then we could get the opposite problem (plus it would involve a lot of shifting code around since currently it assumes the publisher has been looked up first). 

Another option would be to look the publication up by name only if the publisher's name is Unknown and if a publication is found with that name then to assume that it is the right publication and publisher and fix the publisher at that point. This may be the most palatable option on the face of it, and also wouldn't require too much fooling with the code.

**Comment by hading** [comment]
Not necessarily a real-world situation, but what if you had two publishers and they had journals with the same names? This occurs to me as I think about trying a parallel lookup of the publisher and publication and only then, based on the results of that, figuring out what is and is not 'Unknown'. In real life it'd be simpler to proceed as previously described.

**Comment by hading** [comment]
I've reasonably well convinced myself that the fix I suggested above is right. So the change would be if there is a set_publisher with name 'Unknown' then start by doing the publication lookup on name only. If one is found, then see if it has a publisher - if so, then reset the publisher information to use that publisher. If not, then allow things to proceed as before.

**Comment by hading** [comment]
Made modification suggested above in commit a0c6f2a. I still think there is potential mischief in some situations, but this should fix the immediate issue.

**Comment by waingram** [comment]
I like the second option.

**Comment by hading** [comment]
On 6/20/2011 4:40 PM, waingram wrote:

> I like the second option.
> ]
> Good, because that's what I did. :-)
> 
> > -----Original Message-----
> > From: hading [mailto:reply+i-1051002-
> > e15fb7579a264d4642cc13fad2defb56e2d73f9a@reply.github.com]
> > Sent: Monday, June 20, 2011 14:55
> > To: waingram@gmail.com
> > Subject: Re: [BibApp] Duplicate publication created (#20)
> > 
> > A non-technical comment before I look further to see if this worked in the
> > past - I'm not really sure what the right behavior here is. Note that if the
> > publication name isn't given it will default to 'Unknown', just like the
> > publisher. We could try looking up the publication name first, but then we
> > could get the opposite problem (plus it would involve a lot of shifting code
> > around since currently it assumes the publisher has been looked up first).
> > 
> > Another option would be to look the publication up by name only if the
> > publisher's name is Unknown and if a publication is found with that name
> > then to assume that it is the right publication and publisher and fix the
> > publisher at that point. This may be the most palatable option on the face of
> > it, and also wouldn't require too much fooling with the code.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/BibApp/BibApp/issues/20#issuecomment-1405291

## 

Howard Ding
hading2@gmail.com
hding2@illinois.edu
