### ISSUE TITLE
SWORD2

### ISSUE THREAD

**Issue by waingram** [BibApp/BibApp#25]
http://code.cottagelabs.com/sword2ruby

Update our SWORD-client plugin to use SWORD2.

**Comment by hading** [comment]
Is that based off the old one? If so it might be nothing more that removing the current plugin, adding this, and changing SwordClient to Sword2Client in a few places.

**Comment by waingram** [comment]
Sort of. This is just the SWORD2 ruby gem -- maybe not even a gem at this point. But I think you're right, we should just be able to substitute the current SWORD gem with this one. Our client _should_ still work the same.

**Comment by hading** [comment]
working on this. First step is to verify the current setup. Made some changes in order to bring some long untouched code up to date. Needed to change access for servicedocument and deposit to http from https (this is not good, but I'm doing it from my development set up for now). At that point the service document is obtainable from test.ideals.illinois.edu/sword/servicedocument. A deposit still fails with an Internal Server Error. Looking at the Dspace logs this is caused by:

Caused by: org.xml.sax.SAXParseException: The prefix "epdcx" for element "epdcx:descriptionSet" is not bound.

So now I'm at the point of trying to figure that out.

**Comment by hading** [comment]
Okay, adding the xmlns to the document that is generated kills that error, but now our test server gives:

2011-12-08 12:47:30,538 ERROR org.dspace.sword.SWORDMETSIngester @ caught exception: 
org.dspace.core.PluginInstantiationException: Cannot load plugin class: java.lang.ClassNotFoundException: org.dspace.content.authority.SolrAuthority

I'm not sure I can do anything about that right now. I'm going to switch back to the demo.dspace.org server and see how I fare there with the above change.

**Comment by hading** [comment]
Nope, back to the internal server error.

**Comment by hading** [comment]
Okay, it appears that the above ClassNotFoundException has to do with the ongoing upgrade currently being worked out on our test server. At least Bill says it's the same as an error that he keeps seeing in other contexts.

Since I can't see the logs on demo.dspace.org I guess the next step is to resurrect the dspace I have running on my local machine and see what I can do with that.

**Comment by hading** [comment]
Okay, I've managed to deposit into a local dspace 1.8.0. That's something.

Still get an error on the dspace demo server, but that's no surprise.

At least now I know that the 1.3 client is working properly.

**Comment by hading** [comment]
Note that it's also a valid issue that not everything provides a 2.0 server at this point (e.g. it only appeared in Dspace 1.8). So it might be a good idea to have some backwards compatibility instead of simply replacing things. I have to think about that some more. I don't think that the extant Ruby sword2 client provides any sort of backwards compatibility, though I need to check that to be sure.

**Comment by hading** [comment]
Note that it's also possible either that 1.3 and 2.0 are compatible for the things that 1.3 does or even more weakly that they are for the limited things that Bibapp does. I also need to look into that. I haven't seen anything in what searching I've done so far to indicate that they are, but it would be nice.

**Comment by hading** [comment]
As things are now it's possible to retrieve the servicedocument and to post to the repository using the Sword2Client with a Sword1.3 server. The latter works like follows:

sc = Sword2Client.new

sc.execute("post", "collection", sc.config['default_collection_url'], "/home/hading/tmp/example.zip", {}, {'Content-Type' => 'application/zip', 'X-Verbose' => 'true', 'X-No-Op' => 'false', 'Content-Disposition' => 'filename=example.zip', 'X-Packaging' => 'http://purl.org/net/sword-types/METSDSpaceSIP'})

The former is just sc.repo.servicedoc.

Now for depositing that code actually makes the document, but what happens after the post is made and we return to the return_response method in sword2_client.rb is wrong. It throws an error trying to create the deposit receipt. I think here the response body may be different between 1.3 and 2. But if we could hook in there we could perhaps go all the way with the Sword2 client.

Actually it looks like the response body returned is in fact an atom:entry, so I'm not sure why a depositreceipt isn't being made.

**Comment by hading** [comment]
Oh, I'm not sure that the interface to Atom that depositreceipt.rb is using is still good. It tries to call Atom::Entry.load_entry(@source), but in the console Atom::Entry claims not to have such a method. The error handling is masking that that is going on.

**Comment by hading** [comment]
So maybe a different Atom library is being used? The one just called 'atom' on rubygems is really old.

**Comment by hading** [comment]
Yes, the gemfile for the plugin indicates that ratom is used. Let me try that.

**Comment by hading** [comment]
Atom::Entry.load_entry(response.body) is having trouble with a time value. 

ree-1.8.7-2011.03 :006 > Atom::Entry.load_entry(atom)
ArgumentError: argument out of range
    from /home/hading/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/time.rb:180:in `utc'
    from /home/hading/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/time.rb:180:in`make_time'
    from /home/hading/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/time.rb:243:in `parse'
    from /home/hading/.rvm/gems/ree-1.8.7-2011.03@bibapp-rails3/gems/ratom-0.5.2/lib/atom/xml/parser.rb:357:in`build'

**Comment by hading** [comment]
Perhaps this is the atom:updated element?

 atom:updated2011-12-08T22:49:59Z/atom:updated

Or it may be:

atom:published2001-02/atom:published

Perhaps a problem that this doesn't have a day.

**Comment by hading** [comment]
There's the problem - we need to provide the published with a day. I'm not sure how to deal with this. It may be that both Bibapp and Dspace can handle the ambiguity and it's just the atom parser that can't. In fact that appears to be the case. So we'd have to fix it on the Atom parser or where the sword client uses the atom parser.

**Comment by hading** [comment]
It looks like the atom spec demands a fairly precise date to be in atom:published, so maybe it's DSpace's fault for not returning enough information. Of course it doesn't really have a great way to do so.

**Comment by hading** [comment]
It looks like this element isn't required for an atom:entry, so we could hack the sword2client to see if it is a legitimate time (if Time.parse will take it) and if not just remove the element before letting Atom::Entry try to parse it.

**Comment by hading** [comment]
We don't use this field from the return anyway, so that should work.

So in sum, I think we can use the Sword2 client to deal with Sword1.3 servers for what we do in Bibapp - if I can hack it a little bit. I need to check on the licensing. In fact then I could just add a couple of 1.3 compatibility things to it, have a config option for that, and then be set up to deal with Sword2 servers when I want.

**Comment by hading** [comment]
All right, this is basically done and will be pushed soon.

A slight adaptation of the original sword2ruby code is now in the BibApp project. It's abusable to submit to 1.3 servers. In fact, currently BibApp still only does that. But the code that interfaces BibApp with Sword is now abstracted into a Sword_1_3_Adapter class. This implicitly outlines what has to happen for Bibapp to work with a Sword 2 server. It also implicitly provides a way to configure and use adapters for Sword versions other than 1.3, although I haven't done any of that yet.
