### ISSUE TITLE
Publication date defaults to year-01-01

### ISSUE THREAD

**Issue by sshreeves** [BibApp/BibApp#40]
BibApp allows you to specify the date of publication down to the day, which is good. However, for many items there is no day or month of publication, just a year. In the current configuration, if you only specify a year, it looks like BibApp defaults to year-01-01 rather than just the year. This is confusing and often just wrong. We should be able to specify just the year without any month or day information. It would also be useful to be able to specify just a year and month with no day specification.

**Comment by hading** [comment]
Clearly this would be useful. As Bibapp is currently structured I'm not sure how to pull it off. The publication date is stored as a ruby Date, so by definition has a year/month/day to it. The two ideas that come to mind:
- Change the field to be some other type of object. We could make (or find) a simple "AmbiguousDate" class and use that somehow. Presumably it'd be simple enough that we could persist it (using Rails ability to serialize an object into a string/text field).
- Add a flag field that tells how ambiguous the date is, e.g. allow it to be specified as 'day', 'month', or 'year' and format publication date accordingly when it is shown, but still store it as a normal date.

I don't really like either of these solutions, but there may be little else to do. I'll think about it some more.

**Comment by hading** [comment]
Unfortunately the publication_date appears to touch a lot of different places too, although I don't know currently how seriously.

**Comment by hading** [comment]
Publication Date is entered/edited via forms by a Rails date picker. When importing I have no idea what we might get. So the solution needs to play well with this as well. The Rails date picker does allow for blanks, but I'm not sure how that interacts with things.

In short this is not a trivial project.

(Thinking about it a little more - I think something magic happens when you do update_parameters and the hash you pass in has stuff from the Rails date_picker for a date field. It appears that at that point it converts the blanks to 1s if necessary.)

**Comment by hading** [comment]
Another idea would be to split the publication date into publication_date_year, publication_date_month, and publication_date_day.  There could then be a publication_date method to put it back together respecting missing pieces, one to put it together but fill in missing pieces (if need be). There could also be validations to ensure that year is present if anything else is, month is between 1-12 if present, and if day is present then month is present and day is appropriate for the month/year combination. 

An advantage of this approach is that there are some sorts on publication_date when retrieving information. This sort would be trivial to do in this scheme. 

It would also be easy to convert the existing database to this scheme. 

The harder part with this idea is the need to redo the views. We either lose the Rails date_picker functionality or at least have to intercept and massage the results in the controller. It's probably cleaner to just redo it entirely.

I'm again not sure how this would interact with the import functionality. We probably need to do some work, but perhaps it can skip the part where the citation is parsed and be done only when a work is actually created.  But I suspect the problems here will be more or less the same regardless of what scheme we pick.

**Comment by hading** [comment]
Regarding the imports - there is a considerable chunk of code in base_importer.rb devoted to parsing the date as given by the citation data into a 'proper' Ruby date. So something like '2011' gets transformed to a Date representing 2011-01-01 right there and then put into the hash representing the work as :publication_date => '2011-01-01'. 

I'm not sure how much of a problem it would be to convert this to the above scheme. The parsing uses a lot of different cases that can probably be broken down to return something acceptable. E.g. for my above example there is a method that explicitly looks for something that might just be a year. Etc. So these methods could be redone to, instead of returning a Date to return the pieces, blank if appropriate.

Also note that the way Work#update_from_hash works now it assumes that a validation error that happens has to do with the absence of title primary. To be honest, though, I'm not sure exactly why it's coded the way it is. I think it's not used so much that it might be easy to change though. Specifically I would:

If there's an exception, instead of catching it in update_from_hash let the caller deal with it.
Return whether or not the update succeeds.
Let the caller inspect the work to see if there were validation errors.

Returning the id of the work is kind of useless, because the caller already has access to that via the work itself.

**Comment by hading** [comment]
So here's a work plan for this:
- Clean up the return scheme of Work#update_from_hash. This can be done in master directly. Note that callers of create_from_hash also need to be dealt with, as an update_from_hash is the last statement in that method. It probably makes sense to return the created Work as the true value (or the updated work in update_from_hash) for update/create success, and false or nil on failure. Note that create_from_hash/update_from_hash are not heavily used, so this shouldn't be too bad.
- Make another git checkout for this. This will potentially involve some amount of time with a different database scheme, so
  I'd want to use a checkout with a different database.yml and a copy of the database.
- shutdown bibapp
- Migration to add new columns, migrate current data to new p_d_year/month/day format, and remove old column. Note that this migration is reversible. 
- Fix Index, which indexes the year of the publication date and has some other stuff that touches it.
- restart bibapp and reindex all
- Validation scheme for Work with this in place.
- Fix views to be able to generate what they need from new scheme.
- Fix edit/new views/actions for Work to replace date_select with individual selects for each piece. Make sure the information is passed through to the Work create/update methods usably.
- Fix importing. Presumably the previous step would have introduced replacements in the hash for :publication_date, and it would just be a matter of taking advantage of that.

**Comment by hading** [comment]
Actually it'll work a little bit better for update_from_hash and create_from_hash to return the work in all cases and let the caller check whether there are any errors on the work (the caller won't know the work ahead of time for creation). Still throw the error out of them if one occurs.

**Comment by hading** [comment]
I believe I have the first point taken care of now.

**Comment by hading** [comment]
I have a local branch through the validations now.

**Comment by hading** [comment]
Another possible improvement would be to add a bit of javascript to keep the selects in line when entering a date - even if I don't go as far as to ensure that the day is always valid.

**Comment by hading** [comment]
After thinking about it some more, another possibly good solution to this problem would have been to introduce a PublicationDate model with the properties that we wanted and to associate one of these with each work. This would provide essentially the same thing as what I'm doing while taking the code out of the hefty Work class and making it more reusable. I'm not going to revise to go down that road now, but it should actually be an easy change to make in the future if desired.

**Comment by hading** [comment]
Okay, I think I've gotten through up to the last part now.

**Comment by hading** [comment]
I think I have the importing fixed. I'm testing it through the interface now. If it looks good I may need to review the tests for citation_importer and fix some of those. Then this should be good to go on master. I'm not sure how taking it to other branches is going to go, but we'll see.

Oh, there should also be some refactoring opportunities in BaseImporter.

**Comment by hading** [comment]
All right, I think I have everything ready to go here. Just need to make a few last checks.

**Comment by hading** [comment]
Okay, this code is pushed. I just want to try to deploy it to connectionstest and play there a bit before getting it on connections and closing this issue.

**Comment by hading** [comment]
Seems okay on ConnectionsTest, so I will close this and get it on Connections.
