### ISSUE TITLE
Import flow broken, contributorships manageable prior to accepting import

### ISSUE THREAD

**Issue by cjuergen** [BibApp/BibApp#49]
The simplified (see details at http://www.gliffy.com/publish/1371391/ )
flow for an import should be
import citations for a person -> status processing
import processed -> status reviewable
reject -> status rejected
or
accept -> status accepted

After having been accepted the works can be associated with persons via the management of contributorships. Once the works are associated with a person, the works appear in BibApp as works.

I noted that directly after the import has been processed, the works appear in the manage contributorships section and can be associated with a person and after having done so, the works appear as works in BibApp, while the import remains reviewable and rejectable.

**Comment by hading** [comment]
This is how the code for imports is written now. It should flow just as you describe initially above. No contributorships should be created on the works until after they have been accepted (in fact the method create_contributorships on Work specifically checks for this). 

I'm not sure why you are seeing something different, but I am thinking about it. It is conceivable that something else is able to create contributorships besides a Work, but I don't know that offhand. (If this is happening then I should perhaps consolidate the code for creating a new contributorship into Contributorship and make everything else a client of it so that it will work more consistently - however a lot of this stuff is still messy).

**Comment by hading** [comment]
It looks like what happens (as far as managing contributorships) is that the Works are actually created when the Import goes reviewable, via the batch_import method. But part of the callback machinery in saving works is to create the contributorships. Note that at the later stage of accepting an import we explicitly create contributorships, so we don't need to do it in batch_import.

It seems to me that the cleanest solution here is to add a parameter to Work.create_from_hash that specifies that the work is being created from an import. Then we can use that to suppress the callback in that case. I don't think that import is the only thing that uses create_from_hash, but if it is then it should be even simpler.

**Comment by hading** [comment]
create_from_hash is also used by WorksController.

**Comment by hading** [comment]
Oops, accidentally closed this.

**Comment by hading** [comment]
I have a local fix that prevents the contributorship from being made until the right time.

**Comment by hading** [comment]
Okay, that appears to be fine.
